#!/bin/bash

# Stuart Axon 2017 - Use as you will.
#
# return codes
# 1 - issue with archive
# 2 - issue with database
# 3 - issue with destination directory

set -e

shopt -s nullglob
shopt -s dotglob

WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-localhost}
WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}

export MYSQL_PWD=${WORDPRESS_DB_PASSWORD}
export MYSQL="mysql -h${WORDPRESS_DB_HOST} -u${WORDPRESS_DB_USER}"


function dir_empty()
{
    destdir=$1
    files=("${destdir}/"*)
    file_count=${#files[@]}
    if [ ${file_count} -gt 2 ]; then
        return 1
    else
        return 0
    fi
}

function db_is_populated() {
    table_count=$(${MYSQL} --batch --raw -N -e "select count(*) from information_schema.tables where table_schema='wordpress';")
    if [ ${table_count} -gt 0 ]; then
        return 1
    else
        return 0
    fi
}

function db_restore()
{
    SQL=$1
    eval "${MYSQL} --batch --raw -N -D${WORDPRESS_DB_NAME} < $1"
}

function db_update_urls()
{
SQL="
SET @url:='$1';
SET @oldurl:= (SELECT option_value FROM wp_options WHERE option_name = 'siteurl');

UPDATE wp_options
SET    option_value = @url WHERE option_name = 'siteurl' OR option_name = 'home';

UPDATE wp_posts
SET    post_content = Replace(post_content, @oldurl, @url);

UPDATE wp_posts
SET    guid = Replace(guid, @oldurl, @url);

UPDATE wp_posts
SET    post_content = Replace(post_content, @oldurl, @url);

UPDATE wp_postmeta
SET    meta_value = Replace(meta_value, @oldurl, @url);
"

${MYSQL} -D${WORDPRESS_DB_NAME} -e "${SQL}"

}


function archive_is_duplicate()
{
    archive=$1
    # check it's a duplicator archive, with: database.sql wp-config.php
    unzip -l ${archive} database.sql wp-config.php | grep -o '2 files' > /dev/null
    if [ "$?" -ne 0 ]; then
        return 1
    else
        return 0
    fi
}

function db_create()
{
    # don't die here if the db is already created, there is a later
    # check to make sure it is empty.
    ${MYSQL} -e "CREATE DATABASE ${WORDPRESS_DB_NAME};" 2> /dev/null || /bin/true
}

function db_drop()
{
    # don't die here if the db is already created, there is a later
    # check to make sure it is empty.
    ${MYSQL} -e "DROP DATABASE ${WORDPRESS_DB_NAME};" 2> /dev/null || /bin/true
}

function files_restore()
{
    archive=$1
    destdir=$2
    unzip ${archive} -x database.sql -d ${destdir}
}

function wp_configure()
{
    wp_conf=$1
    cp wp-config.php wp-config.php.bak
    sed -i "/DB_HOST/s/'[^']*'/'${WORDPRESS_DB_HOST}'/2" ${wp_conf}
    sed -i "/DB_NAME/s/'[^']*'/'${WORDPRESS_DB_NAME}'/2" ${wp_conf}
    sed -i "/DB_USER/s/'[^']*'/'${WORDPRESS_DB_USER}'/2" ${wp_conf}
    sed -i "/DB_PASSWORD/s/'[^']*'/'${WORDPRESS_DB_PASSWORD}'/2" ${wp_conf}
}

function apache_configure()
{
    apache_conf=$1
    if [ -n ${WORDPRESS_URL} ]; then
        echo ServerName ${WORDPRESS_URL} >> ${apache_conf}
    fi
    a2enmod rewrite
}

function restore_duplicate()
{
    archive=$1
    echo "Restore database"
    tmpdir=$(mktemp -d /tmp/duperestore.XXXXXXXXX)
    mkdir -p ${tmpdir}
    unzip -q ${archive} database.sql -d ${tmpdir}

    db_restore ${tmpdir}/database.sql
    if [ -n ${WORDPRESS_URL} ]; then
        echo "Update urls to ${WORDPRESS_URL}" 1>&2
        db_update_urls ${WORDPRESS_URL}
    else
        echo Not updating urls
    fi

    rm ${tmpdir}/database.sql
    rmdir ${tmpdir}

    dir_empty ${destdir}
    if [ "$3" = "--overwrite" ] || [ $? -eq 0 ]; then
        echo "Restore files..." 1>&2
        files_restore ${archive} ${destdir}
        echo "wp_configure ..." 1>&2
        wp_configure ${destdir}/wp-config.php
        echo "apache_configure ..." 1>&2
        apache_configure '/etc/apache2/apache2.conf'
    else
        echo "Destination directory already populated, not restoring" 1>&2
        return 3
    fi
}

function usage () {
# Using a here doc with standard out.
cat <<-END
Usage:
------
   restore-duplicate <duplicate-archive.zip> <dest_dir>

   duplicate-archive - archive generated by the Wordpress Duplicator plugin.
   destdir           - empty directory setup as an apache docroot.

   Environment variable, default:

    WORDPRESS_DB_HOST       localhost
    WORDPRESS_DB_USER       wordpress
    WORDPRESS_DB_PASSWORD   password

    WORDPRESS_URL

    If set then the script will attempt to update the database and apache to
    use this url.
END
}

function main()
{
    if [ $# -lt 2 ]; then
        echo $#
        echo $*
        usage
        exit
    fi

    archive=$1
    destdir=$2    

    archive_is_duplicate ${archive}
    if [ $? -eq 1 ]; then
        echo "${archive} was not created by wordpress-duplicator" 1>&2
        exit 1
    fi

    if [ "$3" = "--overwrite" ]; then
        rm -rf ${destdir}/* ${destdir}/.??*
    fi
    db_create

    db_is_populated
    if [ "$3" = "--overwrite" ] && [ $? -eq 0 ]; then
        restore_duplicate ${archive} ${destdir} $3
        exit $?

    else
        echo "Database already has tables, not restoring" 1>&2
        exit 2
    fi
}

main $*
